### ISSUE TITLE
Feature: add edit links at the top of the screen

### ISSUE THREAD

**Issue by tbertels** [marczoutendijk/openpoimap#1]
Currently, the edit links appear when we click on a POI.
However:
- If there aren't any POI in the area, there is no way to quickly edit the area
- If there is a POI but not just next to the one we want to add, the edit area will be shifted

Proposed fix: add the edit links at the top of the screen, next to the OpenPoiMap box (or below it).
![presse-papiers-1](https://cloud.githubusercontent.com/assets/3265870/11499109/ff97115a-9823-11e5-91b1-ed1f7ff1f19b.png)

**Comment by marczoutendijk** [comment]
Thank you for that idea! 
Sometimes I experienced that same problem myself.
I'll start working on it.

**Comment by marczoutendijk** [comment]
In the development version I have added your request.
http://www.taglocator.nl
Could you check it and comment on it?
Thanks!

**Comment by tbertels** [comment]
It looks and works great, thanks!
Nonetheless, I have two suggestions:
- add the real links instead of # to the menu items, so that a middle click (to force open a new tab) will work too
- you may want to let know to the user that these menu items open a new tab/window by using an icon like ![external link icon](http://webaim.org/techniques/hypertext/media/external5.png) at the end

**Comment by marczoutendijk** [comment]
Your 2nd suggestion was easy to add and is now available in the development version.
Your first suggestion is more difficult to implement because the link has to be computed based on what is shown in the user window and the zoomlevel. This information becomes only available after the user has clicked on his choice.
But what is the use of that functionality? The link is opening a new tab anyway!

**Comment by tbertels** [comment]
Indeed, with that icon we now know that a middle click is useless.
