### ISSUE TITLE
Feature: replace the Permalink by a dynamic url change

### ISSUE THREAD

**Issue by tbertels** [marczoutendijk/openpoimap#2]
Using history.replaceState(), the Permalink isn't needed anymore since the browser url changes dynamically. And the browser page can be easily refreshed to check for changes on osm.

See https://developer.mozilla.org/en-US/docs/Web/API/History_API#Adding_and_modifying_history_entries for the details.

So you can use this:
`window.history.replaceState(“”, “OpenPoiMap - Taglocator”, “/~marczoutendijk/openpoimap/taglocator.html?map=amenity&zoom=[zoom]&lat=[lat]&lon=[lon]&layers=[layers]”);`
The variable parameters being `[zoom]`, `[lat]`, `[lon]` and `[layers]` (without []).

**Comment by marczoutendijk** [comment]
I'll have a look at that! Thanks.

**Comment by marczoutendijk** [comment]
Tried it, but cannot get it to work.
Is this function a replacement for the Permalink? Why? That is working as expected.

**Comment by tbertels** [comment]
Yes, if it worked, the url bar would get updated in real time, like on osm.
It seems that osm has stopped using OpenLayers (which includes the Permalink).

**Comment by marczoutendijk** [comment]
> Op 13 jan. 2016, om 17:31 heeft Thomas Bertels notifications@github.com het volgende geschreven:
> 
> Yes, if it worked, the url bar would get updated in real time, like on osm.
> It seems that osm has stopped using OpenLayers (which includes the Permalink).

No, Permalink is absolutely working, just try http://openpoimap.org http://openpoimap.org/ instead of the testversion you have used.
If you want to use Permalink in the testversion (www.taglocator.nl http://www.taglocator.nl/), you should right-click on the Permalink and copy/save the link.
This has to do with the way I hide the real website address for the testversion. It is redirected.

Within a few days you’ll find the edit/view button (on top of the screen) also in openpoimap.

Marc.

**Comment by tbertels** [comment]
Yes, the Permalink works, I meant the dynamic url change.

That's great news!
